[profile.default]
libs = ["lib"]
out = "out"
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
src = "src"
#viaIR = true # if we are use more stack we use this line ot compile the code

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
